# Generated by Django 4.0.3 on 2022-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('continente', models.CharField(max_length=25)),
                ('capital', models.CharField(primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('paisdeorigen', models.CharField(max_length=40)),
                ('codigopostal', models.IntegerField(primary_key=True)),
            ],
        ),
    ]
